// $Id$

#include "context.h"

#if 0

// This function is generated by the code generator(!).
extern void __hlt_execution_context_new(hlt_vthread_id vid);

hlt_execution_ctx* hlt_execution_context_new(hlt_vthread_id vid, yield_func* func)
{
    hlt_exceution_ctx* ctx = __hlt_execution_context_new(vid);
    ctx->yield->succ = func;
    ctx->yield->frame = 0;
    ctx->yield->eoss = 0;
    return ctx;
}
#endif
