// $Id$

#ifndef HILTI_RUN_H
#define HILTI_RUN_H

#include "exceptions.h"

// Enters a HILTI program from C. Autogenerated during the HILTI compilation process.
extern void main_run(hlt_exception** excpt);

// Enters a multithreaded HILTI program from C, setting up the appropriate threading
// environment before entering HILTI and tearing it down afterwards.
extern void hilti_multithreaded_run(hlt_exception** hilti_except);

#endif


