#! /usr/bin/env bash
#
# This is preliminary. Eventually, configure will insert the right
# paths here.
#
# FIXME: --debug should work independent of where it is given.

function usage {
   cat <<EOF
Usage: binpac-config <options>

    --cflags        Print flags for C compiler.
    --cxxflags      Print flags for C++ compiler.
    --distbase      Print path of the BinPAC source distribution.
    --bppflags       Print flags for bp++.
    --hiltic        Print flags for hiltic.
    --ldflags       Print flags for linker.
    --libs-bc       Print bitcode libaries LLVM linker.
    --libs-c        Print native libaries for system linker.
    --pythonpath    Print PYTHONPATH for BinPAC module.
    --path          Print PATH for BinPAC tools.

    --debug         Print all output suitable for building debugging versions.
                    Note: this options must come first currently.
    --version       Print BinPAC version.

EOF
   exit 1
}

### Determine distbase.

base=$BINPAC_BASE

if [ "$base" == "" ]; then
   # Try to find the binpac distribution based on our path.

   # If we are called via a symbolic link, dereference it.
   link=`readlink $0`
   if [ "$link" != "" ]; then
       dir=`dirname $link`
   else
       dir=`dirname $0`
   fi

   base=`cd $dir/../../ && pwd -P`
fi

if [ ! -d "$base/libbinpac" ]; then
    echo "cannot determine binpac directory; please set BINPAC_BASE correctly"
    exit 1
fi

### Parse command line.

if [ "$#" == "0" ]; then
   usage
fi

debug=""

builddir="build-release"
libbase="binpac"

while [ "$1" != "" ]; do
    case $1 in
        --version)
            echo "BinPAC++ 0.1"
            shift;;

        --distbase)
            echo $base
            shift;;

        --ldflags)
            echo "-L$base/libbinpac/$builddir"
            shift;;

        --libs-bc)
            echo "-l$libbase"
            shift;;

        --libs-c)
            echo ""
            shift;;

        --bppflags)
            if [ "$debug" == "" ]; then
                #echo ""
                echo "-I$base/libbinpac"
            else
                #echo "-d"
                echo "-I$base/libbinpac -d"
            fi
            shift;;

        --hiltic)
            if [ "$debug" == "" ]; then
                echo "-I$base/libbinpac"
            else
                echo "-I$base/libbinpac -d"
            fi
            shift;;

        --libbinpac)
            echo "$base/libbinpac"
            shift;;

        --cflags)
            echo "-I$base/libbinpac -I$base/libbinpac/$builddir"
            shift;;

        --cxxflags)
            echo "-I$base/libbinpac -I$base/libbinpac/$builddir"
            shift;;

        --pythonpath)
            echo "$base"
            shift;;

        --path)
            echo "$base/tools/binpac++"
            shift;;

        --debug)
            debug=1
            builddir="build-debug"
            libbase="binpacdbg"
            shift;;

        -h)
            usage;;
        *)
            usage;;
    esac
done




