// $Id$

#include <stdio.h>

#include "memory.h"
#include "context.h"
#include "rtti.h"

// Generated by the HILTI linker. It tells us how many bytes we need to store
// all thread-global variables.⎈
extern int64_t __hlt_globals_size;

// These functions initialize/destroy all the globals in the passed context
// to their default values. They are normally generated by the HILTI linker,
// but we provide a "weak" dummy implementation in case no module needs any of this.
__attribute__ ((weak)) void __hlt_globals_init(hlt_execution_context* ctx) {}
__attribute__ ((weak)) void __hlt_globals_dtor(hlt_execution_context* ctx) {}

void hlt_execution_context_dtor(hlt_execution_context* ctx)
{
    __hlt_globals_dtor(ctx);
}

__HLT_RTTI_GC_TYPE(hlt_execution_context, HLT_TYPE_CONTEXT)

hlt_execution_context* __hlt_execution_context_new(hlt_vthread_id vid)
{
    hlt_execution_context* ctx = (hlt_execution_context*)
        GC_NEW_CUSTOM_SIZE(hlt_execution_context, sizeof(hlt_execution_context) + __hlt_globals_size);

    ctx->vid = vid;

    __hlt_globals_init(ctx);

    return ctx;
}
