// $Id$

#include <stdio.h>

#include "memory.h"
#include "context.h"
#include "rtti.h"
#include "globals.h"
#include "exceptions.h"
#include "config.h"

// Generated by the HILTI linker. It tells us how many bytes we need to store
// all thread-global variables.⎈
extern int64_t __hlt_globals_size;

// These functions initialize/destroy all the globals in the passed context
// to their default values. They are normally generated by the HILTI linker,
// but we provide a "weak" dummy implementation in case no module needs any of this.
__attribute__ ((weak)) void __hlt_globals_init(hlt_exception** excpt, hlt_execution_context* ctx) {}
__attribute__ ((weak)) void __hlt_globals_dtor(hlt_exception** excpt, hlt_execution_context* ctx) {}

void hlt_execution_context_dtor(hlt_type_info* ti, hlt_execution_context* ctx)
{
    hlt_exception* excpt = 0;
    __hlt_globals_dtor(&excpt, ctx);

    if ( excpt ) {
        fprintf(stderr, "global deinitialization threw exception\n");
        exit(1);
    }

    GC_DTOR(ctx->excpt, hlt_exception);
}

__HLT_RTTI_GC_TYPE(hlt_execution_context, HLT_TYPE_CONTEXT)

hlt_execution_context* __hlt_execution_context_new(hlt_vthread_id vid)
{
    hlt_execution_context* ctx = (hlt_execution_context*)
        GC_NEW_CUSTOM_SIZE(hlt_execution_context, sizeof(hlt_execution_context) + __hlt_globals_size);

    ctx->vid = vid;

    hlt_exception* excpt = 0;
    __hlt_globals_init(&excpt, ctx);

    if ( excpt ) {
        fprintf(stderr, "global initialization threw exception\n");
        exit(1);
    }

    ctx->excpt = 0;
    ctx->fiber = hlt_fiber_create(hlt_config_get()->stack_size);

    return ctx;
}

void __hlt_context_set_exception(hlt_exception* excpt, hlt_execution_context* ctx)
{
    GC_ASSIGN(ctx->excpt, excpt, hlt_exception);
}

hlt_exception* __hlt_context_get_exception(hlt_execution_context* ctx)
{
    return ctx->excpt;
}

void __hlt_context_clear_exception(hlt_execution_context* ctx)
{
    GC_CLEAR(ctx->excpt, hlt_exception);
}
