
#include <locale.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

#include "types.h"
#include "config.h"
#include "debug.h"
#include "globals.h"
#include "hook.h"
#include "threading.h"
#include "profiler.h"

// This is generated by the HILTI linker to initialize all the modules.
extern __hlt_modules_init(hlt_exception** excpt, hlt_execution_context* ctx);

// Debugging support to flag wrong usage of hlt_init/hlt_exit.
static int _init_called = 0;
static int _done_called = 0;

static void _check_for_done()
{
    if ( ! _done_called ) {
        fprintf(stderr, "libhilti: hlt_done() not called at termination, aborting\n");
        _exit(1);
    }
}

void hlt_init()
{
    if ( _init_called ) {
        fprintf(stderr, "libhilti: hlt_init() called multiple times, aborting\n");
        exit(1);
    }

    _init_called = 1;

    // Initialize locale.
    if ( ! setlocale(LC_CTYPE, "") ) {
        fprintf(stderr, "libhilti: cannot set locale");
        exit(1);
    }

    __hlt_config_init();
    __hlt_debug_init();
    __hlt_cmd_queue_init();
    __hlt_global_state_init();
    __hlt_hooks_init();
    __hlt_threading_init();
    __hlt_profiler_init();

    hlt_execution_context* ctx = hlt_global_execution_context();
    hlt_exception* excpt = 0;
    __hlt_modules_init(&excpt, ctx);

    if ( excpt )
        __hlt_exception_print_uncaught_abort(excpt, ctx);

    atexit(_check_for_done);
}

void hlt_done()
{
    if ( _done_called ) {
        fprintf(stderr, "libhilti: hlt_done() called multiple times, aborting\n");
        exit(1);
    }

    _done_called = 1;

    hlt_exception* excpt = 0;

    __hlt_threading_done(&excpt);
    __hlt_profiler_done(); // Must come after threading is done.

    if ( excpt ) {
        hlt_exception_print_uncaught(excpt, hlt_global_execution_context());
        GC_DTOR(excpt, hlt_exception);
    }

    __hlt_hooks_done();
    __hlt_global_state_done();
    __hlt_cmd_queue_done();
    __hlt_debug_done();
    __hlt_config_done();
}

