///
/// Implementation of main() which directly executes Main::run().
///

#include <getopt.h>
#include <stdio.h>
#include <string.h>

#include <sys/wait.h>

#include "config.h"
#include "context.h"
#include "exceptions.h"
#include "globals.h"
#include "init.h"
#include "types.h"

static struct option long_options[] = {{"threads", required_argument, 0, 't'},
                                       {"profile", no_argument, 0, 'P'},
                                       {0, 0, 0, 0}};

static void usage(const char* prog)
{
    printf(
        "%s [options]\n"
        "\n"
        "  -h | --help                 Show usage information.\n"
        "  -t | --threads <num>        Number of worker threads; zero disables. [Default: 2.]\n"
        "  -P | --profile              Activate profiling support.\n"
        "  -Z | --dump-libhilti-state Dump global libhilti state to stderr for debugging.\n"
        "\n",
        prog);

    exit(1);
}

// Top-level entry point generated by HILTI compiler. We declare out
// implementation weak so the external implementation will override it.
__attribute__((weak)) void main_run(hlt_exception** excpt, hlt_execution_context* ctx)
{
    fprintf(stderr, "<no Main::run() function in HILTI code>\n");
}

// Standalone main() driving command line processing and code execution. We
// declare this weak so that host applications with their own main() function
// can still link against the library/
__attribute__((weak)) int main(int argc, char** argv)
{
    int dump_libhilti_state = 0;

    hlt_config cfg = *hlt_config_get();

    while ( 1 ) {
        char c = getopt_long(argc, argv, "ht:PZ", long_options, 0);

        if ( c == -1 )
            break;

        switch ( c ) {
        case 't':
            cfg.num_workers = atoi(optarg);
            break;

        case 'P':
            cfg.profiling = 1;
            break;

        case 'Z':
            dump_libhilti_state = 1;
            break;

        default:
            usage(argv[0]);
        }
    }

    if ( optind != argc )
        usage(argv[0]);

    hlt_config_set(&cfg);

    hlt_init();

    if ( dump_libhilti_state )
        hlt_global_state_dump(stderr);

    hlt_execution_context* ctx = hlt_global_execution_context();
    hlt_exception* excpt = 0;
    main_run(&excpt, ctx);

    if ( ! excpt )
        return 0;

    hlt_exception_print_uncaught(excpt, hlt_global_execution_context());
    GC_DTOR(excpt, hlt_exception, ctx);

    // TOOD: Should probably return 1 here, but the test-suite currentluy
    // expects the exit code to be zero in the case of unhandled exceptions.
    return 0;
}
