// Prototypes for type information generated by the compiler from
// type-info.hlt. Included by (and after) rtti.h
//
// FIXME: Eventually, hiltic will generate these prototypes for us.

#ifndef HILTI_TYPE_INFO_H
#define HILTI_TYPE_INFO_H

extern const hlt_type_info* hlt_type_info_hlt_int_32;
extern const hlt_type_info* hlt_type_info_hlt_int_64;
extern const hlt_type_info* hlt_type_info_hlt_string;
extern const hlt_type_info* hlt_type_info_hlt_bytes;
extern const hlt_type_info* hlt_type_info_hlt_addr;
extern const hlt_type_info* hlt_type_info_hlt_iterator_bytes;
extern const hlt_type_info* hlt_type_info_hlt_exception;
extern const hlt_type_info* hlt_type_info_hlt_callable;
extern const hlt_type_info* hlt_type_info_hlt_timer;
extern const hlt_type_info* hlt_type_info_hlt_time;
extern const hlt_type_info* hlt_type_info_hlt_timer_mgr;
extern const hlt_type_info* hlt_type_info_hlt_list;
extern const hlt_type_info* hlt_type_info_hlt_iterator_list;
extern const hlt_type_info* hlt_type_info_hlt_vector;
extern const hlt_type_info* hlt_type_info_hlt_iterator_vector;
extern const hlt_type_info* hlt_type_info_hlt_set;
extern const hlt_type_info* hlt_type_info_hlt_iterator_set;
extern const hlt_type_info* hlt_type_info_hlt_map;
extern const hlt_type_info* hlt_type_info_hlt_iterator_map;

#endif
