// Prototypes for type information generated by the compiler from
// type-info.hlt. Included by (and after) rtti.h
//
// FIXME: Eventually, hiltic will generate these prototypes for us.

#ifndef LIBHILTI_TYPE_INFO_H
#define LIBHILTI_TYPE_INFO_H

extern const hlt_type_info hlt_type_info_hlt_int_32;
extern const hlt_type_info hlt_type_info_hlt_int_64;
extern const hlt_type_info hlt_type_info_hlt_string;
extern const hlt_type_info hlt_type_info_hlt_bytes;
extern const hlt_type_info hlt_type_info_hlt_regexp;
extern const hlt_type_info hlt_type_info_hlt_addr;
extern const hlt_type_info hlt_type_info_hlt_iterator_bytes;
extern const hlt_type_info hlt_type_info_hlt_exception;
extern const hlt_type_info hlt_type_info_hlt_callable;
extern const hlt_type_info hlt_type_info_hlt_timer;
extern const hlt_type_info hlt_type_info_hlt_time;
extern const hlt_type_info hlt_type_info_hlt_timer_mgr;
extern const hlt_type_info hlt_type_info_hlt_list;
extern const hlt_type_info hlt_type_info_hlt_iterator_list;
extern const hlt_type_info hlt_type_info_hlt_vector;
extern const hlt_type_info hlt_type_info_hlt_iterator_vector;
extern const hlt_type_info hlt_type_info_hlt_set;
extern const hlt_type_info hlt_type_info_hlt_iterator_set;
extern const hlt_type_info hlt_type_info_hlt_map;
extern const hlt_type_info hlt_type_info_hlt_iterator_map;
extern const hlt_type_info hlt_type_info_hlt_file;
extern const hlt_type_info hlt_type_info_hlt_tuple_iterator_bytes_iterator_bytes;
extern const hlt_type_info hlt_type_info_hlt_match_token_state;
extern const hlt_type_info hlt_type_info_hlt_classifier;
extern const hlt_type_info hlt_type_info_hlt_port;
extern const hlt_type_info hlt_type_info_hlt_iosrc;
extern const hlt_type_info hlt_type_info_hlt_channel;

#endif
