#! /usr/bin/env bash
#
# This is preliminary. Eventually, configure will insert the right
# paths here.
#
# FIXME: --debug should work independent of where it is given.

function usage {
   cat <<EOF
Usage: hilti-config <options>

    --cflags       Print flags for llvm-gcc.
    --cxxflags     Print flags for llvm-g++.
    --distbase     Print path of the HILTI source distribution.
    --hilticflags  Print flags for hiltic.
    --ldflags      Print flags for llvm-ld.
    --libhilti     Print path to libhilti files.
    --libs-bc      Print bitcode libaries for llvm-ld.
    --libs-bc-main Print bitcode libaries for llvm-ld, including a main() routine.
    --libs-c       Print native libaries for system linker.
    --pythonpath   Print PYTHONPATH for HILTI module.
    --path         Print PATH for HILTI tools.

    --debug        Print all output suitable for building debugging versions.
                   Note: this options must come first currently.
    --version      Print HILTI version.

EOF
   exit 1
}

### Determine distbase.

base=$HILTI_BASE

if [ "$base" == "" ]; then
   # Try to find the HILTI distribution based on our path.

   # If we are called via a symbolic link, dereference it.
   link=`readlink $0`
   if [ "$link" != "" ]; then
       dir=`dirname $link`
   else
       dir=`dirname $0`
   fi

   base=`cd $dir/../../ && pwd -P`
fi

if [ ! -d "$base/libhilti" ]; then
    echo "cannot determine HILTI directory; please set HILTI_BASE correctly"
    exit 1
fi

### Add the libpcap flags

pcap_config=`which pcap-config 2>/dev/null`

if [ "$pcap_config" == "" ]; then
   echo "cannot find pcap-config"
   exit 1
fi

pcap_cflags=`pcap-config --cflags `
pcap_libs=`pcap-config --libs | sed 's/-L /-L/g'` # clang doesn't like spaces.

### Parse command line.

if [ "$#" == "0" ]; then
   usage
fi

debug=""

builddir="build-release"
libpostfix=""

while [ "$1" != "" ]; do
    case $1 in
        --version)
            echo "HILTI 0.1"
            shift;;

        --distbase)
            echo $base
            shift;;

        --ldflags)
            echo "-L$base/libhilti/$builddir -L$base/libhilti/$builddir/justrx/src"
            shift;;

        --libs-bc)
            echo "-lhilti${libpostfix} -ljrx${libpostfix}"
            shift;;

        --libs-bc-main)
            echo "-lhilti${libpostfix} -lhiltimain${libpostfix} -ljrx${libpostfix}"
            shift;;

        --libs-c)
            echo "-lc -lpthread $pcap_libs"
            shift;;

        --hilticflags)
            if [ "$debug" == "" ]; then
                echo "-I$base/libhilti -I$base/libhilti/module"
            else
                echo "-I$base/libhilti -I$base/libhilti/module -d"
            fi
            shift;;

        --cflags)
            echo "-I$base/libhilti -I$base/libhilti/3rdparty/bdwgc/include -g -I$base/libhilti/$builddir $pcap_cflags"
            shift;;

        --cxxflags)
            echo "-I$base/libhilti -I$base/libhilti/3rdparty/bdwgc/include -g -I$base/libhilti/$builddir $pcap_cflags"
            shift;;

        --libhilti)
            echo "$base/libhilti $base/libhilti/module"
            shift;;

        --pythonpath)
            echo "$base"
            shift;;

        --path)
            echo "$base/tools/hiltic:$base/tools/hilti-build:$base/tools/hilti-build2"
            shift;;

        --debug)
            debug=1
            builddir="build-debug"
            libpostfix="dbg"
            shift;;

        -h)
            usage;;
        *)
            usage;;
    esac
done




