#! /usr/bin/env bash
#
# Turns a HILTI source into an executable by compiling, assembling, 
# and linking with libhiltimain. 
#
# Honors the following environment variables to pass additional flags 
# on to the corresponding tools:
#
#     HILTICFLAGS
#     LLVMASFLAGS
#     LLVMLDFLAGS
#     CFLAGS
#
# If HILTIDEPS is set to the hilti-dependency location, paths are
# setup accordingly.

if [ "$HILTIDEPS" != "" -a -e "$HILTIDEPS/bin/setup-paths" ]; then
   eval `$HILTIDEPS/bin/setup-paths`
fi   

function usage {
   echo "Usage: hilti-build [-m] [-t] [-v] -o <output> <input-files>"
   echo 
   echo "Input files may be end in one of the following extensions:"
   echo "    *.hlt     - HILTI files"
   echo "    *.ll      - LLVM assember file"
   echo "    *.bc      - LLVM bitcode files"
   echo
   echo "Options:"
   echo "    -o         Name of output file; mandatory."
   echo "    -m         Link with libhilti instead of libhiltimain."
   echo "    -t         Do not delete temporary files."
   echo "    -v         Output command lines as they are executed."
   echo "    -O1/O2/O3  Apply optimizations (see 'man opt'); also enables LTO."
   echo "    -l obj.bc  Additional object file to link in."
   echo "    -P         Generate only C prototypes for *.hlt files; does nothing else."
   echo "    -c         Produce a native, linkable object file, not an executable."
   echo "    -b         Produce a bitcode file for JITing."
   echo "    -d         Compile HILTI files with debugging support."
   echo
   exit 1 
}

function execute {
    if [ "$verbose" != "" ]; then
       echo $@ >>$verbose
    fi

    eval $@
}

function delete_tmps {
     # Delete at exit.
     if [ "$keeptmp" != "1" ]; then
         rm -f $tmpfiles
     fi
}

# Turns *.hlt into *.ll
function compile_hlt {
    input=$1
    dir=`dirname $input`
    base=`basename $input .hlt`
    
    if [ "$protos" == "1" ]; then
        # Just run hiltic to generate the C prototypes.
        doth=$base.h
        execute "hiltic -P $hilticflags $input -o $doth" || exit 1
        result=$doth;
    else
        # Compile *.hlt into *.ll
        ll=$base.tmp.ll
        tmpfiles="$tmpfiles $ll"
        execute "hiltic -l $hilticflags -o $ll $input" || exit 1
        result=$ll
    fi
}

# Turns *.ll into *.bc
function compile_ll {
    input=$1
    dir=`dirname $input`
    base=`basename $input .ll`

    if [ "$opt" != "" ]; then
        pipeopt="| opt $opt"
    else
        pipeopt=""
    fi

    bc=$base.tmp.bc
    tmpfiles="$tmpfiles $bc"
    execute "llvm-as $llvmasflags < $input $pipeopt >$bc"
    result=$bc
}

# Turns *.c into *.bc
function compile_c {
    input=$1
    dir=`dirname $input`
    base=`basename $input .ll`

    bc=$base.tmp.bc
    tmpfiles="$tmpfiles $bc"
    execute "clang -c -emit-llvm $opt $cflags -o $bc $input"
    result=$bc
}

# Turns *.cc into *.bc
function compile_cc {
    input=$1
    dir=`dirname $input`
    base=`basename $input .ll`

    bc=$base.tmp.bc
    tmpfiles="$tmpfiles $bc"
    execute "llvm-g++ -c -emit-llvm $opt $cxxflags -o $bc $input"
    result=$bc
}

# Links all *.bc together into the final output file.
function link_all {
    bc=$@
    
    execute "llvm-ld -disable-opt -b=$output.bc $llvmldflags $bc $libsbc" || exit 1
    execute "rm $output" || exit 1 # Stupid shell script.

    if [ "$opt" != "" ]; then
        tmpfiles="$tmpfiles $output.opt.bc"
        execute "opt -f $opt $output.bc -o=$output.opt.bc" || exit 1
        execute "mv $output.opt.bc $output.bc"
    fi   

    if [ "$bitcode" != "" ]; then
       # Done.
       return
    fi

    tmpfiles="$tmpfiles $output.bc"
    tmpfiles="$tmpfiles $output.bc.S"

    # Compile into native assembler.
    execute "llc -f -o=$output.bc.S $output.bc" || exit 1
    
    # Assemble into executable code. Seems using the compiler driver is the way to go here ...
    if [ "$noexec" != "" ]; then
        exec="-Xlinker=-r"
    else
        exec=""
    fi   
    
    execute "clang -o $output $exec $llvmldflags $libsc $output.bc.S"
}

function find_libraries {
    result=""
    paths=""
    libs=""
    ext=$1
    shift 

    for flag in $@; do 
        echo $flag | grep -q '^-L'
        if [ $? == 0 ]; then
           paths="$paths `echo $flag | sed 's/^-L//g'`"
        fi
        
        echo $flag | grep -q '^-l'
        if [ $? == 0 ]; then
           libs="$libs `echo $flag | sed 's/^-l//g'`"
        fi
    done
    
    for lib in $libs; do 
        for path in $paths; do 
            full=$path/lib$lib.$ext
            if [ -f $full ]; then
               result="$result $full"
            fi
        done
    done
    
    echo $result
}

tmpfiles=""
inputs=""
protos=""
noexec=""
bitcode=""
debug=""
libsbcflag="--libs-bc-main"

while [ "$1" != "" ]; do
    case $1 in 
        -m)
            libsbcflag="--libs-bc" ; shift;;
        -t)
            keeptmp=1; shift;;
        -v)
            verbose=/dev/stderr; shift;;
        -O1) 
            opt=$1; shift;;
        -O2) 
            opt=$1; shift;;
        -O3) 
            opt=$1; shift;;
        -P)
            protos="1"; shift;;
        -o)
            output=$2; shift; shift;; 
        -c)
            noexec="1"; shift;; 
        -b)
            bitcode="1"; shift;; 
        -d)
            debug="--debug"; shift;; 
        -h) 
            usage;; 
        -*)
            usage;;
        *)
            inputs="$inputs $1"; shift;;
    esac
done    

if [ "$inputs" == "" ]; then
   usage
fi   

if [ "$output" == "" -a "$protos" != "1" ]; then
   echo "name of output file must be given with -o." >&2
   exit 1
fi   

if [ "$TEST_DIAGNOSTICS" != "" ]; then
   keeptmp=1
fi   

trap delete_tmps 0

if [ "$HILTI_CONFIG" != "" ]; then
    hilticonfig=$HILTI_CONFIG
else
    hilticonfig=`which hilti-config 2>/dev/null`
fi    

if [ ! -x "$hilticonfig" ]; then
   echo "cannot find hilti-config; try setting HILTI_CONFIG." >&2
   exit 1
fi

llvmasflags="$LLVMASFLAGS"
hilticflags="`$hilticonfig $debug --hilticflags` $HILTICFLAGS"
llvmldflags="`$hilticonfig $debug --ldflags` $LLVMLDFLAGS"
cflags="`$hilticonfig $debug --cflags` $CFLAGS"
cxxflags="`$hilticonfig $debug --cxxflags` $CFLAGS"
libsbc=`$hilticonfig $libsbcflag`
libsc=`$hilticonfig --libs-c`

export PYTHONPATH=`$hilticonfig --pythonpath`:$PYTHONPATH

input=$@
objs=""

for file in $inputs; do
    
    if echo $file | grep -q '\.hlt$'; then
       compile_hlt $file
       if [ "$protos" != "1" ]; then
           compile_ll $result
       fi
       objs="$objs $result"
       
    elif echo $file | grep -q '\.ll$'; then
       compile_ll $file
       objs="$objs $result"
       
    elif echo $file | grep -q '\.c$'; then
       compile_c $file
       objs="$objs $result"
       
    elif echo $file | grep -q '\.cc$'; then
       compile_cc $file
       objs="$objs $result"
       
    elif echo $file | grep -q '\.bc$' ; then
       objs="$objs $file"
       
    else
       echo "unknown input type $file"
       exit 1
    fi
    
done

if [ "$protos" == "1" ]; then
   # Nothing else to do.
   exit 0;
fi

link_all $objs
