#! /usr/bin/env bash
#
# $Id$
#
# Canonifies a test's output before running test-diff.

# Remove absolute paths from exception information.
sed 's#(from .*/\([^/]\{1,\}\):#(from XXX/\1:#g' | \
sed 's#from filtered-#from #g'
