#! /usr/bin/env bash
#
# Runs the tester with the correct environment variables set.

if [ "$HILTIDEPS" != "" -a -e "$HILTIDEPS/bin/setup-paths" ]; then
   eval `$HILTIDEPS/bin/setup-paths`
fi   

BASE_DIR=`cd ../.. && pwd -P`
TESTER=$BASE_DIR/tester/bin/tester
HILTI_BASE=$BASE_DIR/hilti

unset HILTICFLAGS
unset LLVMASFLAGS
unset LLVMLDFLAGS
unset CFLAGS

export HILTI_CONFIG=$BASE_DIR/hilti/tools/hilti-config/hilti-config

CFLAGS=`$HILTI_CONFIG --cflags`
PYPATH=`$HILTI_CONFIG --pythonpath`

export PATH="$HILTI_BASE/tools/hiltic:$HILTI_BASE/tools/hilti-build:$PATH"
export CC="clang -emit-llvm -g $CFLAGS"

# Set a well-defined locale.
export LANG=C
export LC_ALL=C

$TESTER $@

