
# This Makefile is likely not what you want to use. See the README.

all:
	clang  -I ../../libhilti -I ../../build/libhilti -I ../../libbinpac -I ../../build/libbinpac -fno-color-diagnostics pac-driver.c
