#! /usr/bin/env bash 

driver=`binpac-config --distbase`/tools/pac-driver

export CFLAGS="`binpac-config --cflags` -DHTTP_THREADED"

# export CFLAHS="$CFLAGS -I $driver"
export HILTICFLAGS=`binpac-config --hiltic`

rm -f http-concat.tmp.hlt
cat pachttp.hlt http.hlt >http-concat.tmp.hlt
chmod -w http-concat.tmp.hlt

hilti-build2 $driver/pac-driver.c -d -v http-concat.tmp.hlt $@


