#! /usr/bin/env bash -x

pac=$1

export CFLAGS=`binpac-config --cflags`
export HILTICFLAGS=`binpac-config --hiltic`

binpac++ $pac -o $pac.hlt || exit 1
hilti-build -o pac-driver pac-driver.c $pac.hlt 


