#! /usr/bin/env python
#
# Reads flow-ids from stdin and extracts the corresponding content from $1
# into individual files.

import sys

flows = set()

for line in sys.stdin:
    line = line.split()
    
    flows.add(line[0])

files = {}
    
data = open(sys.argv[1])

while True:
    
    line = data.readline()
    
    if not line:
        break
        
    if not line.startswith("# "):
        print >>sys.stderr, "format error in", sys.argv[1]
        sys.exit(1)
        
    m = line.split()

    kind = m[1]
    dir = m[2]
    len = int(m[3])
    flow = m[4]
    
    fid = flow + "#" + dir
    
    if kind == "G":
        continue
    
    if kind == "D":
        chunk = data.read(len)
        
        if fid in flows:
            if fid not in files:
                fname = "contents.%s.%s.dat" % ("orig" if dir == ">" else "resp", flow)
                fname = fname.replace("/", "-")
                files[fid] = open(fname, "wb")
                
                print "Extracting", fname
            
            files[fid].write(chunk)
        
    if kind == "T":
        
        if  fid in files:
            files[fid].close()
            del files[fid]
    
        continue
