#! /usr/bin/env bash

# Arguments to GC's CMakeLists.txt Note that the parallel_mark is untried yet,
# as is incremental collection.
GC_CMAKE="-Denable_threads=YES -Denable_parallel_mark=NO"

# Additional arguments to the C compiler when compiling the GC. 
GC_CFLAGS="-DGC_THREADS -D_REENTRANT"

# Further C compiler flags for the debugging version. We just all
#debugging stuff we can find ...
GC_CFLAGS_DEBUG="-DGC_DEBUG -DGC_ASSERTIONS -DMAKE_BACK_GRAPH -DDBG_HDRS_ALL -DKEEP_BACK_PTRS"

function build {
    dir=$1          # Build directory.
    cmake_flags=$2  # cmake flags for libhilti.
    gc=$3           # C compiler flags for GC.

    base=`pwd`/$1

	# Create directories.
    for d in $base $base/3rdparty $base/3rdparty/bdwgc; do
		test -e $d || mkdir $d
    done

	cwd=`pwd`

    # Build libgc.
    cd $base/3rdparty/bdwgc
    test -e Makefile || CFLAGS=$gc cmake $GC_CMAKE ../../../3rdparty/bdwgc
    make

    # Build libhilti.
    cd $base
    test -e Makefile || cmake $cmake_flags ..
    make

    cd $cwd
}

echo
echo =============
echo Release Build
echo =============
echo

build build-release "-DLLVM_ENABLE_DEBUG=0"  "$GC_CFLAGS"

echo
echo ===========
echo Debug Build
echo ===========
echo

build build-debug   "-DLLVM_ENABLE_DEBUG=1 " "$GC_CFLAGS $GC_CFLAGS_DEBUG"

