#! /usr/bin/env python

import sys
import operator

tags = {}

total_cycles = 0

for line in sys.stdin:

	if line.startswith("#!"):
		# Parse header and cache indices we need.
		t = {}

		m = line.split()[1:]

		for i in range(len(m)):
			t[m[i]] = i

		idx_tag = t["tag"]
		idx_type = t["type"]
		idx_cycles = t["cycles"]

	if line.startswith("#"):
		continue

	m = line.split()

	tag = m[idx_tag]
	type = m[idx_type]
	cycles = int(m[idx_cycles])

#	if type == "B":
#		tags[tag] = tags.get(tag, 0) - cycles
#		total_cycles = total_cycles - cycles
#	elif type == "E":
#		tags[tag] = tags.get(tag, 0) + cycles
#		total_cycles = total_cycles + cycles

	if type == "E":
		tags[tag] = tags.get(tag, 0) + cycles
		total_cycles = total_cycles + cycles


for (tag, val) in sorted(tags.iteritems(), key=operator.itemgetter(1), reverse=True):
	print "%10.2f%%   %s" % (100.0 * val / total_cycles, tag)

