#! /usr/bin/env bash

tmp=`basename $0`.$$.tmp

cat | grep hilti-mem | sed 's/ref<\([^>]*\)>/\1/g' | sed 's/[:(),]/ /g' >$tmp

cat $tmp | awk '

    { idx = $4; 

      if ( $2 == "cctor" || $2 == "new" )
          ref[idx] += 1;

      if ( $2 == "dtor" )
          ref[idx] -= 1;

    }

END {
    for ( i in ref )
        printf "%40s %5d\n", i, ref[i];

    }

' | sort -b

echo
echo ------
echo

cat $tmp | grep hilti-mem | sed 's/[:(),]/ /g' | awk '

    { idx = $3 " " $4 ; 

      if ( $2 == "cctor" || $2 == "new" )
          ref[idx] += 1;

      if ( $2 == "dtor" )
          ref[idx] -= 1;

    }

END {
    for ( i in ref )
        printf "%60s %5d\n", i, ref[i];

    }

' | sort -b


rm -f $tmp
