#! /usr/bin/env python
#
# Parses the output from HILTI_DEBUG=hilti-mem from stdin and reports on memory leaks.
#
# If -v is given, reports details for every leak.

import sys
import optparse

optparser = optparse.OptionParser(usage="%prog [options] <input-file>")

optparser.add_option("-v", "--verbose", action="store_true", dest="verbose", default=False,
                     help="include detailed output for leaks")

(options, args) = optparser.parse_args()

if len(args) != 0:
	optparser.error("too many arguments")

objs = {}

for line in sys.stdin:

	if not line.startswith("[hilti-mem]"):
		continue

	m = line.split()

	(dbg, op, addr, size, refcnt, type, location) = m[0:7]

	if op == "free":
		del objs[addr]
		continue

	try:
		objs[addr] += [(op, line)]
	except KeyError:
		objs[addr] = [(op, line)]

leaks = 0

for lines in objs.values():
    for (op, line) in lines:
        if op == "dtor" or op == "cctor":
            continue

        leaks += 1

if not leaks:
	sys.exit(0)

print "Leaks"
print "====="
print

for (obj, lines) in objs.items():

    (op, line) = lines[0]

    if op == "dtor" or op == "cctor":
        continue

    print "  ", line,
    
if options.verbose:
    print
    print
    print "Details"
    print "======="
    print

    for (obj, lines) in objs.items():
        first = True
        for (op, line) in lines:
            if op == "dtor" or op == "cctor":
                continue

            print ("/ " if first else "| "), line,
            first = False

        if not first:
            print ""

sys.exit(1)
