#! /usr/bin/env bash
#
# Returns the path of Bro distribution in use.

function abspath
{
    (cd "$1" && pwd)
}

base=`dirname $0`
build=`${base}/get-cmake-var BRO_PLUGIN_BRO_BUILD`
echo `abspath $build/..`
