#! /usr/bin/env bash

hilticonfig="../../../hilti/tools/hilti-config/hilti-config"
binpacconfig="../../tools/binpac-config/binpac-config"

tools=`$hilticonfig --distbase`/tools
hiltic=`$binpacconfig --hiltic`

export PATH=$tools/hilti-config:$PATH

$tools/hiltic/hiltic $hiltic -l $1 | llvm-as >$2
