#! /usr/bin/env bash
#
# This is preliminary. Eventually, configure will insert the right
# paths here.

function usage {
   cat <<EOF
Usage: hilti-config <options>

    --cflags              Print flags for C compiler.
    --cxxflags            Print flags for C++ compiler.
    --distbase            Print path of the HILTI source distribution.
    --hiltic-binary       Print path of hiltic binary
    --hiltic-flags        Print flags for hiltic.
    --hiltic-flags-main   Print flags for hiltic to link libhiltimain
    --ldflags             Print flags for llvm-ld.
    --libhilti            Print path to libhilti.
    --libs                Print system libraries for llvm-ld.
    --prefix              Print path of installation (TODO: same as --distbase currently)

    --debug               Adapt all output for building debugging versions.

    --version             Print HILTI version.
EOF
   exit 1
}

function release_or_debug {
    std=$1
    dbg=$2

    if [ "$debug" == "" ]; then
        echo $std
    else
        echo $dbg $std
    fi
}

### Determine distbase.

base=$HILTI_BASE

if [ "$base" == "" ]; then
   # Try to find the HILTI distribution based on our path.

   # If we are called via a symbolic link, dereference it.
   link=`readlink $0`
   if [ "$link" != "" ]; then
       dir=`dirname $link`
   else
       dir=`dirname $0`
   fi

   base=`cd $dir/.. && pwd -P`
fi

if [ ! -d "$base/libhilti" ]; then
    echo "cannot determine HILTI directory; please set HILTI_BASE correctly"
    exit 1
fi

### Add the libpcap flags.

# pcap_config=`which pcap-config 2>/dev/null`
#
# if [ "$pcap_config" == "" ]; then
#    echo "cannot find pcap-config"
#    exit 1
# fi
#
# pcap_cflags=`pcap-config --cflags `
# pcap_libs=`pcap-config --libs | sed 's/-L /-L/g'` # clang doesn't like spaces.

### Parse command line once to see if we have --debug in there.

build_mode="release"

for arg in $@; do
    if [ "$arg" == "--debug" ]; then
        debug=1
        build_mode="debug"
        libpostfix="-dbg"
    fi
done

### Now parse the rest.

while [ "$1" != "" ]; do
    case $1 in
        --version)
            echo "HILTI 0.2"
            shift;;

        --distbase)
            echo $base
            shift;;

        --prefix)
            # No installation yet.
            echo $base
            shift;;

        --libsflags)
            echo ""
            shift;;

        --ldflags)
            echo ""
            shift;;

        --hiltic-flags)
            echo "$base/libhilti/type-info.hlt $base/build/libhilti-${build_mode}/libhilti-rt${libpostfix}.bca -I$base/libhilti"
            shift;;

        --hiltic-flags-main)
            echo "$base/libhilti/type-info.hlt $base/build/libhilti-${build_mode}/libhilti-rt-main${libpostfix}.bca -I$base/libhilti"
            shift;;

        --libhilti)
            echo "$base/libhilti"
            shift;;

        --libs)
            ## This is a hack. Eventually, cmake should replace this directlt *.in style.
            ## papi_libs=`cat $base/libhilti/$builddir/papi-libs.cfg`
            # echo "-lc -lm -lpthread $papi_libs $pcap_libs"
            echo "$base/build/libhilti-${build_mode}/libhilti-rt-native.a"
            shift;;

        --cflags | --cxxflags)
            echo "-I$base/libhilti -I$base/libhilti/$builddir"
            shift;;

        --hiltic-binary)
            echo "$base/build/tools/hiltic"
            shift;;

        --debug)
            # Done in first pass already.
            shift;;

        -h)
            usage;;
        *)
            usage;;
    esac
done




