
MESSAGE(STATUS "Final values for build mode ${CMAKE_BUILD_TYPE}:")

MESSAGE(STATUS "    C_COMPILER:   ${CMAKE_C_COMPILER}")
MESSAGE(STATUS "    CXX_COMPILER: ${CMAKE_CXX_COMPILER}")
MESSAGE(STATUS "    C_FLAGS:      ${CMAKE_C_FLAGS}")
MESSAGE(STATUS "    CXX_FLAGS:    ${CMAKE_CXX_FLAGS}")

