#! /usr/bin/env bash
#
# This scripts extractes the number of current allocations from
# pac-driver's "-g" output and counts how  many different values we
# see. For input/grammars where memory should be released frequently,
# there should only be a small number of values.

grep allocations | sed 's/.*alloced, //g' | sed 's/ allocations.*//g' | sort | uniq | wc -l | awk '{print $1;}'
