#! /usr/bin/env bash

tmp=`basename $0`.$$.tmp

cat >$tmp

# Don't have these.
if egrep -q '%0 = bitcast i8\* %__ctx to %hlt.execution_context.0' $tmp; then
    echo "Pattern unexpectedly found"
    rm -f $tmp
    exit 1
fi

# Have these.
if ! egrep -q 'attributes #0 = \{ nounwind readnone \}' $tmp; then
    echo "Expected pattern not found"
    rm -f $tmp
    exit 1
fi

rm -f $tmp


