#! /usr/bin/env bash
#
# Finalizer run after every test. If there's a hlt-debug.log file, we
# run it through mem-check to find leaks. If there are any, we let the
# test fail.
#
# Note that HILTI_DEBUG needs to be set to "hilti-mem" to log memory
# information. btest.cfg does that.

LOG="hlt-debug.log"

if [ ! -e $LOG ]; then
    # No log file, that's ok.
    return 0
fi

cat $LOG | `dirname $0`/../../scripts/mem-check -v >&2
