#! /usr/bin/env bash
#
# Finalizer run after every test. If there's a hlt-debug.log file, we
# run it through mem-check to find leaks. If there are any, we let the
# test fail.
#
# Note that HILTI_DEBUG needs to be set to "hilti-mem" to log memory
# information. btest.cfg does that.
#
# If there's no hlt-debug, we report that by default unless the user tells
# us it's ok for this test by updating the baseline.

LOG="hlt-debug.log"

if [ ! -e $LOG ]; then
    # No log file.
    # echo "--- No hlt-debug.log for memory checking." >no-debug.log
    # exec btest-diff no-debug.log

    # That's ok.
    exit 0
fi

if [ $($(dirname $0)/../../build/tools/hilti-config --build) == "release" ]; then
    # Cannot use leak checking in release mode, as many of the tests
    # still pull in the debug library, leading to mismatches.
    export NO_LEAK_CHECK=1
fi

if [ "$NO_LEAK_CHECK" == "" ]; then
    cat $LOG | `dirname $0`/../../scripts/mem-check -v >&2
fi
